### ISSUE TITLE
VRAM very high usage issue.

### ISSUE THREAD

**Issue by DavideAlidosi** [jhj0517/stable-diffusion-webui-MusePose#4]
I am testing the extension, and I have noticed that there is an abnormal use of VRAM to the point that it is unusable even on a 3090.
I'm using all defaut settings, but still the processing is well over 30GB.
With the same settings in ComfyUI, 17GB of maximum usage is never exceeded.
Thanks for the support.

**Comment by Rubenacp** [comment]
Yes, I also did some tests and the same thing happened, but I tried to reduce the resolution to 512 or less as recommended in the original repository, but I always output it to 768. Possibly the resolution settings are not working correctly and that is why it is always so high the use of vram and ram

**Comment by Dawgmastah** [comment]
You can output higher but need to modify both pose_align and the test2py

**Comment by jhj0517** [comment]
I don't know why this happens, It's very difficult to reproduce with my GPU.
I'm finding what caused this.

**Comment by jhj0517** [comment]
Tried to release vram after each run in #6

**Comment by DavideAlidosi** [comment]
I doubt it is a problem related to the release of VRAM, as it occurs in the first generation.
In the attached image I have included the current settings, and the loading status of my VRAM.
Of course, before doing the test I updated to the latest commit.
I also attach my input documents, in case they are needed. I also used the same assets on ComfyUI without any problems.
Thanks again.

https://github.com/jhj0517/stable-diffusion-webui-MusePose/assets/19665235/0b8ea308-98f8-42e9-bb68-4aad197d11c1

![image_test](https://github.com/jhj0517/stable-diffusion-webui-MusePose/assets/19665235/be2b30d0-e14e-4853-985b-3422d8e5af8a)
![Memory Leak](https://github.com/jhj0517/stable-diffusion-webui-MusePose/assets/19665235/3333a0e4-4f2a-4de9-9e12-013228dc2690)

**Comment by DavideAlidosi** [comment]
I did some additional testing, from what I could see it seems that the `Compute Type` selector is not working properly. In fact using the 16 or 32 bit float varies the VRAM consumption, which should be higher in the second case.
This leads me to believe that the system is always working at 32bit, which would justify the higher amount of VRAM used compared to ComfyUI.

**Comment by DavideAlidosi** [comment]
I've fix it! The issue is into the UI selector, in the file `musepose_inference.py at line 77` change:
`if weight_dtype == "fp16":`
to
`if weight_dtype == "float16":`

**Comment by jhj0517** [comment]
@DavideAlidosi 
Thanks so much for letting me know. Merged #7 and is now fixed.

**Comment by Rubenacp** [comment]
Thanks, it works
